// Code generated by hertz generator.

package image_tagger

import (
	"code.byted.org/middleware/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getimagesMw() []app.HandlerFunc {
	// your code...
	return nil
}
