// Code generated by hertztool. DO NOT EDIT.

package router

import (
	"code.byted.org/middleware/hertz/pkg/app/server"
	comfyui_image_tagger "github.com/w43322/ComfyUI/image_tagger/biz/router/comfyui/image_tagger"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	comfyui_image_tagger.Register(r)

}
