// Code generated by hertztool. DO NOT EDIT.

package main

import (
	"code.byted.org/middleware/hertz/pkg/app/server"
	router "github.com/w43322/ComfyUI/image_tagger/biz/router"
)

// register registers all routers.
func register(r *server.Hertz) {

	router.GeneratedRegister(r)

	customizedRegister(r)

}
