// Code generated by hertztool

package main

import (
	"code.byted.org/middleware/hertz/pkg/app/server"
	handler "github.com/w43322/ComfyUI/image_tagger/biz/handler"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...
	r.Static("/output", "/Users/bytedance/git/ComfyUI")
}
