// Code generated by hertztool.

package handler

import (
	"context"
	images "github.com/w43322/ComfyUI/image_tagger/src"
	"strings"

	"code.byted.org/middleware/hertz/pkg/app"
	"code.byted.org/middleware/hertz_ext/v2/binding"
	image_tagger "github.com/w43322/ComfyUI/image_tagger/biz/model/comfyui/image_tagger"
)

// GetImages .
// @router /get_images [GET]
func GetImages(ctx context.Context, c *app.RequestContext) {
	var err error
	var req image_tagger.GetImagesReq
	err = binding.BindAndValidate(c, &req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(image_tagger.GetImagesResp)
	err = binding.WriteHeader(c, resp)
	if err != nil {
		c.String(500, err.Error())
		return
	}

	tagsStr, _ := c.GetQuery("tags")
	tags := strings.Split(tagsStr, ",")
	resp.Images = images.GetImages(tags)

	c.JSON(200, resp)
}
